table main_accounts
	isHidden
	lineageTag: dd091bd2-69fa-4aef-a5b8-641791851798

	column 'Account Name'
		dataType: string
		isHidden
		lineageTag: b4ec96dc-88ee-4bbf-a185-5b3694dee7fa
		summarizeBy: none
		sourceColumn: Account Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column headcount
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cce9ae9b-3d16-4111-be4e-6ec62a2ba8cb
		summarizeBy: sum
		sourceColumn: headcount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column hubspot_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d1d54981-5574-4c0a-a7f6-8564a1800289
		summarizeBy: count
		sourceColumn: hubspot_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		isHidden
		lineageTag: d53a7ff7-89b4-46b2-9e8c-588fe2c39617
		summarizeBy: none
		sourceColumn: Branch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column segmentation_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f2e7b0b5-08cc-47d9-80b1-dac884869197
		summarizeBy: none
		sourceColumn: segmentation_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Service Line'
		dataType: string
		isHidden
		lineageTag: 1e1b95f7-722e-42e5-9f1e-063397b1ddc7
		summarizeBy: none
		sourceColumn: Service Line

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		isHidden
		lineageTag: 9b2bfcf9-1cb9-4233-b0c8-b6f78489a6a2
		summarizeBy: none
		sourceColumn: Industry

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aniversary_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: abd5c53f-1873-4fac-bc54-c0ab49c6bcf5
		summarizeBy: none
		sourceColumn: aniversary_date

		variation Variation
			isDefault
			relationship: 6a3880bb-3d98-4a39-bd50-bd42b6dea28a
			defaultHierarchy: LocalDateTable_035d96b5-a5bf-4a54-8321-1176922fdda7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Enterprise date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3e079c16-0078-4df4-88da-03dd6eff086b
		summarizeBy: none
		sourceColumn: Enterprise date

		variation Variation
			isDefault
			relationship: 1726cf58-3f49-4b0f-b012-47373a62ba21
			defaultHierarchy: LocalDateTable_09d350a0-5ee0-4c83-867a-e0453675d735.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column churn_finance
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: b11006c4-0610-4865-9bcb-a5fa97fac76a
		summarizeBy: none
		sourceColumn: churn_finance

		variation Variation
			isDefault
			relationship: 8541b0a2-36d3-4fdb-92b2-4d639eb11bf7
			defaultHierarchy: LocalDateTable_5f264127-ab1c-49ea-9673-0745079f2d61.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition main_accounts = m
		mode: import
		queryGroup: 'Accounts Info'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://perfilesysoluciones.sharepoint.com/sites/PerformanceManagement83/Shared%20Documents/Corporate%20BI/Accounts/Account%20Names%20and%20Finance%20Distribution.xlsx"), null, true),
				    main_accounts_Table = Source{[Item="main_accounts",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(main_accounts_Table,{{"Account Name", type text}, {"headcount", Int64.Type}, {"hubspot_ID", Int64.Type}, {"Branch", type text}, {"segmentation_ID", Int64.Type}, {"Service Line", type text}, {"Industry", type text}, {"aniversary_date", type date}, {"Enterprise date", type date}, {"churn_finance", type date}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

